name: maisondbm
favicon: null
layout_spectrum: 0.9915795302949846
typography_spectrum: 0.3351943565066904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.20005412446334958
  lightness: 0.47417813586071134
  saturation: 0.5069895808119327
  rhythmicContrast: 0.3335341131314635
purpose: []
